name: xsalon_mobile
description: "Мобильное приложение для салонов красоты XSalon"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Supabase
  supabase_flutter: ^2.0.0
  
  # Navigation
  go_router: ^12.1.3
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Date & Time
  table_calendar: ^3.0.9
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Network
  dio: ^5.4.0
  
  # Utils
  uuid: ^4.2.1
  logger: ^2.0.2+1
  flutter_dotenv: ^5.1.0
  intl: ^0.20.2
  
  # Permissions
  permission_handler: ^11.1.0
  
  # Image
  image_picker: ^1.0.4
  
  # Phone
  mask_text_input_formatter: ^2.7.0
  
  # SMS & OTP
  pinput: ^3.0.1
  
  # Loading & Animations
  loading_animation_widget: ^1.2.0+4
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env
  
